# .github/workflows/build-and-test.yml
name: Build and Test
on:
  push:
jobs:
  hawkscan:
    name: Build and Test
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Build the app
        run: docker-compose build
      - name: Run the app
        run: docker-compose up --detach
      - name: Scan the app
        uses: stackhawk/hawkscan-action@v1.3.2
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
